In [46]:
import numpy as np
a = np.asmatrix([[22,5,16,9],[13,20,19,0],[5,9,1,16],[27,13,15,19]])
b = np.asmatrix([[10,5,20,20], [5,21,22,27], [26,19,22,3], [27,8,18,7]])
c = np.array([24, 3, 17, 7, 11, 2, 21, 2, 24, 18, 3, 11, 14, 25, 2, 20])
d = np.array([3, 15, 24, 22, 19, 24, 4, 29, 6, 3, 20, 1, 11, 25, 26, 6])
#
print(a)
print(b)
print(c)
print(d)


[[22  5 16  9]
 [13 20 19  0]
 [ 5  9  1 16]
 [27 13 15 19]]
[[10  5 20 20]
 [ 5 21 22 27]
 [26 19 22  3]
 [27  8 18  7]]
[24  3 17  7 11  2 21  2 24 18  3 11 14 25  2 20]
[ 3 15 24 22 19 24  4 29  6  3 20  1 11 25 26  6]


In [36]:
#1 addition
print(a + b)

[[32 10 36 29]
 [18 41 41 27]
 [31 28 23 19]
 [54 21 33 26]]


In [10]:
#2 substraction
print(a-b)

[[ 12   0  -4 -11]
 [  8  -1  -3 -27]
 [-21 -10 -21  13]
 [  0   5  -3  12]]


In [17]:
#3 multiplication
print(a * b)

[[ 904  591 1064  686]
 [ 724  846 1118  857]
 [ 553  361  608  458]
 [1238  845 1498 1069]]


In [37]:
#4 multiplication
print(np.dot(a, b))

[[ 904  591 1064  686]
 [ 724  846 1118  857]
 [ 553  361  608  458]
 [1238  845 1498 1069]]


In [21]:
#5
print(c+d)

[27 18 41 29 30 26 25 31 30 21 23 12 25 50 28 26]


In [23]:
#6
print(c-d)

[ 21 -12  -7 -15  -8 -22  17 -27  18  15 -17  10   3   0 -24  14]


In [25]:
#7
print(c*d)

[ 72  45 408 154 209  48  84  58 144  54  60  11 154 625  52 120]


In [27]:
#8
print(np.dot(c, d))

2298


In [29]:
#9
print(a+10)

[[32 15 26 19]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]


In [30]:
#10
print(b+10)

[[20 15 30 30]
 [15 31 32 37]
 [36 29 32 13]
 [37 18 28 17]]


In [32]:
#11
print(c+15)

[39 18 32 22 26 17 36 17 39 33 18 26 29 40 17 35]


In [47]:
#12
print(d+15)

[18 30 39 37 34 39 19 44 21 18 35 16 26 40 41 21]


In [51]:
#13


print((2*a) + (2*b))

[[ 64  20  72  58]
 [ 36  82  82  54]
 [ 62  56  46  38]
 [108  42  66  52]]


In [52]:
#14
print((a+b) * 3)

[[ 96  30 108  87]
 [ 54 123 123  81]
 [ 93  84  69  57]
 [162  63  99  78]]


In [55]:
#15
print((a- b + a - b + b) * 4)

[[ 136   20   48   -8]
 [  84   76   64 -108]
 [ -64   -4  -80  116]
 [ 108   72   48  124]]
